name: tudu
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_serializable: ^6.7.1
  path_provider: ^2.1.5
  intl: ^0.18.1
  fluttertoast: ^8.2.4
  table_calendar: ^3.0.9
  file_selector: ^1.0.3
  flutter_local_notifications: ^17.1.1
  permission_handler: ^11.3.0
  timezone: ^0.9.4
  flutter_timezone: ^4.1.1
  android_alarm_manager_plus: ^4.0.7
  android_intent_plus: ^5.3.0
  device_info_plus: ^11.5.0
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  
flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/dots.png
    - assets/pageMark.png
    - assets/emptyTaskImg.png
    - assets/emptytaskArrow.png
    - assets/addTaskPlus.png
    - assets/addTaskArrowBack.png
    - assets/calender_icon.png
    - assets/updown.png
    - assets/loudAlertOn.png
    - assets/loudAlertOff.png
    - assets/mediumAlertOn.png
    - assets/mediumAlertOff.png
    - assets/dropDownArrow.png
    - assets/addTaskIcon.png
    - assets/editIcon.png
    - assets/loudAlertOn1.png
    - assets/loudAlertOff1.png
    - assets/mediumAlertOn1.png
    - assets/mediumAlertOff1.png
    - assets/taskDone.png
    - assets/taskPending.png
    - assets/dustBin.png
    - assets/tone.png

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
    - family: Quantico
      fonts:
        - asset: fonts/Quantico-Regular.ttf
        - asset: fonts/Quantico-Bold.ttf
          weight: 700


  